#%RAML 1.0

title: menu
version: v1
baseUri: http://menu.nigelaukland.com
types:
  Recipe:
    properties:
      name: string
      description: string
      imagePath: string
    example:
      name: "Tandoori Tilapia"
      description: "The recipe from James Martin"
      imagePath: "https://i.dailymail.co.uk/i/pix/2011/03/11/article-0-0D30A321000005DC-986_468x419.jpg"
resourceTypes:
  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
    post:
      body:
        application/json:
          type: <<item>>
  Member:
    put:
      body:
        application/json:
          type: <<item>>
    delete:
      responses:
        204:
/recipes:
  type:  { Collection: {item : Recipe} }
  /{id}:
    type:  { Member: {item : Recipe} }
