#%RAML 1.0

title: menu
version: v1
baseUri: http://menu-api.nigelaukland.com
types:
  recipe:
    properties:
      id: string
      name: string
      description: string
      imagePath: string
    example:
      id: "123456789abcdef"
      name: "Tandoori Tilapia"
      description: "The recipe from James Martin"
      imagePath: "https://i.dailymail.co.uk/i/pix/2011/03/11/article-0-0D30A321000005DC-986_468x419.jpg"
  dayMenu:
    properties:
      id: string 
      date: date-only
      morningText: string
      morningRecipeId: string 
      lunchText: string
      lunchRecipeId: string
      dinnerText: string
      dinnerRecipeId: string
    example:
      id: "123456789abcdef"
      date: "2018-04-21"
      morningText: "No need for breakfast"
      morningRecipeId: "123456789abcdef" 
      lunchText: "Picnic lunch"
      lunchRecipeId: "123456789abcdef"
      dinnerText: "Out for dinner"
      dinnerRecipeId: "123456789abcdef"
  menu:
    properties:
      id: string
      name: string
      startDate: date-only
      dayMenuIds: string[]
    example:
      id: "123456789abcdef"
      name: "Weekly menu"
      startDate: "2018-04-21"
      dayMenuIds: ["123456789abcdef", "123456789abcdef"]

resourceTypes:
  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
    post:
      body:
        application/json:
          type: <<item>>
  Member:
    put:
      body:
        application/json:
          type: <<item>>
    delete:
      responses:
        204:

/menus:
  type: { Collection: {item : menu} }
  /{id}:
    type: { Member: {item : menu} }

/dayMenus:
  type:  { Collection: {item: dayMenu} }
  /{id}:
    type:  { Member: {item: dayMenu} }

/recipes:
  type:  { Collection: {item : recipe} }
  /{id}:
    type:  { Member: {item : recipe} }

